name: VISION
channels:
  - conda-forge
  - https://conda.anaconda.org/gurobi
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - aom=3.5.0
  - asttokens=2.4.1
  - attr=2.5.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.22.1
  - ca-certificates=2023.11.17
  - cairo=1.16.0
  - certifi=2023.11.17
  - cfitsio=3.470
  - cloudpickle=2.0.0
  - comm=0.1.4
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2021.10.0
  - dbus=1.13.6
  - debugpy=1.6.3
  - decorator=5.1.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - expat=2.5.0
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.25.0
  - freeglut=3.2.2
  - freetype=2.12.1
  - fsspec=2022.11.0
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.78.1
  - glib-tools=2.78.1
  - gmp=6.3.0
  - gnutls=3.7.8
  - graphite2=1.3.13
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.34
  - harfbuzz=5.3.0
  - hdf5=1.12.2
  - icu=70.1
  - imageio=2.19.3
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - ipykernel=6.16.2
  - ipython=7.33.0
  - jack=1.9.22
  - jasper=2.0.33
  - jedi=0.19.1
  - joblib=1.1.1
  - jpeg=9e
  - jupyter_client=7.4.9
  - jupyter_core=4.11.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.1.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=8.1.2
  - libdb=6.2.32
  - libdeflate=1.14
  - libdrm=2.4.114
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgcrypt=1.10.2
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.1
  - libglu=9.0.0
  - libgomp=13.2.0
  - libgpg-error=1.47
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libogg=1.3.4
  - libopenblas=0.3.24
  - libopencv=4.6.0
  - libopus=1.3.1
  - libpciaccess=0.17
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=3.21.12
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.44.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libsystemd0=253
  - libtasn1=4.19.0
  - libtiff=4.4.0
  - libtool=2.4.7
  - libudev1=253
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - locket=1.0.0
  - lz4-c=1.9.4
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mpg123=1.32.3
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - nettle=3.8.1
  - networkx=2.6.3
  - nspr=4.35
  - nss=3.94
  - numpy=1.21.6
  - opencv=4.6.0
  - openh264=2.3.1
  - openssl=3.1.4
  - p11-kit=0.24.1
  - packaging=23.2
  - parso=0.8.3
  - partd=1.2.0
  - pcre=8.41
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.3.1
  - pixman=0.42.2
  - platformdirs=4.0.0
  - ply=3.11
  - prompt-toolkit=3.0.41
  - prompt_toolkit=3.0.41
  - psutil=5.9.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pure_eval=0.2.2
  - py-opencv=4.6.0
  - pygments=2.17.1
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.7.12
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pywavelets=1.3.0
  - pyyaml=6.0
  - pyzmq=24.0.1
  - qt-main=5.15.6
  - readline=8.2
  - scikit-image=0.19.3
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=68.2.2
  - sip=6.7.2
  - six=1.16.0
  - sqlite=3.44.0
  - stack_data=0.6.2
  - svt-av1=1.4.1
  - threadpoolctl=2.2.0
  - tifffile=2020.10.1
  - tk=8.6.13
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - traitlets=5.9.0
  - typing_extensions=4.7.1
  - tzdata=2023c
  - wcwidth=0.2.10
  - wheel=0.41.3
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.10
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
